### ISSUE TITLE
blugon.service: Main process exited, code=exited, status=11/n/a

### ISSUE THREAD

**Issue by frankruegamer** [jumper149/blugon#1]
I noticed that the blugon service wasn't running after reboot. journalctl showed 

```
-- Reboot --
Jan 16 18:02:03 archlinux systemd[1029]: Started Blue Light Filter.
Jan 16 18:02:04 archlinux systemd[1029]: blugon.service: Main process exited, code=exited, status=11/n/a
Jan 16 18:02:04 archlinux systemd[1029]: blugon.service: Failed with result 'exit-code'.
Jan 16 18:02:04 archlinux systemd[1029]: blugon.service: Service RestartSec=100ms expired, scheduling restart.
Jan 16 18:02:04 archlinux systemd[1029]: blugon.service: Scheduled restart job, restart counter is at 1.
Jan 16 18:02:04 archlinux systemd[1029]: Stopped Blue Light Filter.
```

The following 4 tries failed the same way.

I installed blugon using the AUR, and I'm using X, lightdm and awesomeWM.
Starting the service manually works fine.

**Comment by jumper149** [comment]
Doesn't the service restart afterwards?
Failing once or a few times is normal because blugon is waiting for the DISPLAY environment variable to be set by X (thats what exit status=11 means).

So as long as

    Jan 16 18:02:04 archlinux systemd[1029]: blugon.service: Scheduled restart job, restart counter is at 1.
restarts it it should be fine.

For me it is looking like this:

    Jan 18 16:11:33 deskarch systemd[590]: blugon.service: Scheduled restart job, restart counter is at 1.
    Jan 18 16:11:33 deskarch systemd[590]: Stopped Blue Light Filter.
    Jan 18 16:11:33 deskarch systemd[590]: Started Blue Light Filter.
and then it runs until I stop it or shutdown.

I am not very knowledgeable when it comes to systemd, but is there maybe some variable that prevents the service from restarting?

The [service-file](https://github.com/jumper149/blugon/blob/master/systemd/user/blugon.service) uses:

    RestartForceExitStatus=11

**Comment by jumper149** [comment]
> How does it work, if DISPLAY is not set does blugon exit immediately or really wait a moment for a change in the variable?

blugon doesn't wait at all. That's why I wanted to use systemd in the first place, so that systemd knows when to start blugon.

After trying around for a bit I got to the following conclusion:
- blugon's startup is supposed to be at `graphical-session.target` (after you login, so blugon can acces your dotfiles)
- it would be possible to either
  - wait longer (> 100ms)
  - try more than 5 times
  - dont exit blugon and wait inside the program until DISPLAY is set (ugly?)
  - is it possible to set a constant delay in systemd?
- it might also be possible to run and configure it as root and then set up a system wide service but that is really not what I wanted to do here because Im afraid whether that's safe and configuration wouldnt be in the dotfiles (would use `graphical.target` then)

I actually found another problem with all this:
When you switch TTY, the `sgc` and `xgamma` backend dont find the X-Server anymore. I'm not sure if I should let it crash then or wait until you switch back to the TTY with X. Maybe checking the DISPLAY variable works again here. I will try this out in the future.

**Comment by frankruegamer** [comment]
Thank you for all the effort and research into this problem. Until now I have started the service manually after login. I have updated to the latest version which seems to show that 5 tries with 1 second between was enough to let the service start.
I'm not quite sure why my pc/configuration seems to take that long to set the DISPLAY variable.  
I haven't fully tested it yet but the 5th try was able to do the trick.

```
Jan 20 16:51:46 archlinux systemd[1019]: Started Blue Light Filter.
Jan 20 16:51:47 archlinux systemd[1019]: blugon.service: Main process exited, code=exited, status=11/n/a
Jan 20 16:51:47 archlinux systemd[1019]: blugon.service: Failed with result 'exit-code'.
Jan 20 16:51:48 archlinux systemd[1019]: blugon.service: Service RestartSec=1s expired, scheduling restart.
Jan 20 16:51:48 archlinux systemd[1019]: blugon.service: Scheduled restart job, restart counter is at 1.
Jan 20 16:51:48 archlinux systemd[1019]: Stopped Blue Light Filter.
Jan 20 16:51:48 archlinux systemd[1019]: Started Blue Light Filter.
Jan 20 16:51:48 archlinux systemd[1019]: blugon.service: Main process exited, code=exited, status=11/n/a
Jan 20 16:51:48 archlinux systemd[1019]: blugon.service: Failed with result 'exit-code'.
Jan 20 16:51:49 archlinux systemd[1019]: blugon.service: Service RestartSec=1s expired, scheduling restart.
Jan 20 16:51:49 archlinux systemd[1019]: blugon.service: Scheduled restart job, restart counter is at 2.
Jan 20 16:51:49 archlinux systemd[1019]: Stopped Blue Light Filter.
Jan 20 16:51:49 archlinux systemd[1019]: Started Blue Light Filter.
Jan 20 16:51:49 archlinux systemd[1019]: blugon.service: Main process exited, code=exited, status=11/n/a
Jan 20 16:51:49 archlinux systemd[1019]: blugon.service: Failed with result 'exit-code'.
Jan 20 16:51:50 archlinux systemd[1019]: blugon.service: Service RestartSec=1s expired, scheduling restart.
Jan 20 16:51:50 archlinux systemd[1019]: blugon.service: Scheduled restart job, restart counter is at 3.
Jan 20 16:51:50 archlinux systemd[1019]: Stopped Blue Light Filter.
Jan 20 16:51:50 archlinux systemd[1019]: Started Blue Light Filter.
Jan 20 16:51:50 archlinux systemd[1019]: blugon.service: Main process exited, code=exited, status=11/n/a
Jan 20 16:51:50 archlinux systemd[1019]: blugon.service: Failed with result 'exit-code'.
Jan 20 16:51:52 archlinux systemd[1019]: blugon.service: Service RestartSec=1s expired, scheduling restart.
Jan 20 16:51:52 archlinux systemd[1019]: blugon.service: Scheduled restart job, restart counter is at 4.
Jan 20 16:51:52 archlinux systemd[1019]: Stopped Blue Light Filter.
Jan 20 16:51:52 archlinux systemd[1019]: Started Blue Light Filter.
```

**Comment by jumper149** [comment]
I had an even better idea just now. Since the start up delay will be different for everyone you can now set the restart interval in the general config.
Just change

    [wait_for_x]
    sleep_after_failed_start-up = 5

For waiting 5 seconds

**Comment by howaboutsynergy** [comment]
I'm inside X but service is still exiting...

```
[  276.259322] systemd[676]: blugon.service: Service RestartSec=10s expired, scheduling restart.
[  276.285244] systemd[676]: blugon.service: Scheduled restart job, restart counter is at 25.
[  276.445069] systemd[676]: blugon.service: Main process exited, code=exited, status=11/n/a
[  276.445433] systemd[676]: blugon.service: Failed with result 'exit-code'.
[  286.509548] systemd[676]: blugon.service: Service RestartSec=10s expired, scheduling restart.
[  286.509883] systemd[676]: blugon.service: Scheduled restart job, restart counter is at 26.
[  286.692817] systemd[676]: blugon.service: Main process exited, code=exited, status=11/n/a
[  286.693109] systemd[676]: blugon.service: Failed with result 'exit-code'.
```
had to set `RestartSec=10`, but now I wonder why it keeps exiting...

**Comment by jumper149** [comment]
The `DISPLAY` environment variable gets set by X.
Blugon starts after X, but X takes its time. I dont know of any option to delay blugon until the `DISPLAY` variable gets set. Thats why there is the workaround with a delay.

    After=graphical-session.target

from https://github.com/jumper149/blugon/blob/master/systemd/user/blugon.service#L4


If you have any idea to fix it please let me know. The systemd service is only supposed to be used, when also running a display manager via systemd. In case you want to use `startx` I would use something like [this](https://github.com/jumper149/dotfiles/blob/master/.xinitrc#L24).

**Comment by howaboutsynergy** [comment]
Thanks so much. I appreciate the `.xinitrc` workaround. I'll try that.
