### ISSUE TITLE
Cannot kill blugon

### ISSUE THREAD

**Issue by vorotynsky** [jumper149/blugon#19]
I installed blugon using yay on Arch with Xorg and i3-gaps. I can't stop it.
```bash
~ $ blugon
^C (ctrl+c)
~ $ killall blugon
blugon: no process found
~ $ kill blugon
kill: illegal pid: blugon
```

`ps -x`, `ps aux`, `gotop` can't find the blugon. Blue filter is still enabled.

**Comment by jumper149** [comment]
I think there are two things going on.

First of all blugon doesn't spawn any child processes (atleast none that don't terminate pretty much instantly). So when you kill it with `ctrl+c` it really is dead.
The color will stay applied because they are changed in the X server. If you want to reset the color you can use `blugon --setcurrent=6600`. This will exit immediately as it implies the `--once` flag.

The other thing that might be confusing and actually wrong in the README is that it can be a little hard to find python processes.
This is because the python file is run by the python interpreter.

```
> ps a
    PID TTY      STAT   TIME COMMAND
    ...
    705 tty1     S      0:00 python3 /usr/bin/blugon --waitforx --fade
    ...
```

Here you could kill it with `kill 705`. A little quicker is:

```
> pkill --full blugon
```

This won't return any message but will have killed a process when it exits successfully.

**Comment by jumper149** [comment]
Will fix README:

https://github.com/jumper149/blugon/blob/55156d83337c077d65e903adacf138cc1cbb883f/README.md#L32
